jwt_secret = "your-secret-key"
database_url = "sqlite:data/users.db?mode=rwc"

[server]
host = "0.0.0.0"
port = 3000

[redis]
host = "localhost"
port = 6379
password = "123456"

[harbor]
url = "http://192.168.41.227:8097"
username = "admin"
password = "Harbor12345"
